### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by buraksaritas** [yusufyildirim/react-native-lightning#4]
> It would be nice to make the README page more professional.

**Comment by ozsirma** [comment]
It will be organized soon...

**Comment by yusufyildirim** [comment]
Hi, I'll do radical changes at this weekend including README page and Wiki section. Have a nice day👍

**Comment by yusufyildirim** [comment]
Hi again,

Our README page has been updated and more commits are coming. We'll keep going 🎉
